### PR TITLE
Add support for working with rendered content to remove the page 'jumps' after truncation

### PR DESCRIPTION
**Pull request by marijngiesen**
This adds support for truncation in hidden elements, so that truncation doesn't cause page 'jumps'. After truncating the hidden element, the element will be cloned and the original rendered content will be overwritten. See README.md for a short explanation.

### CODE REVIEW

**Comment by rviscomi** [comment]
Thanks.

It's impossible to check the diff of the js file because it seems you've changed the spacing of the file (tabs/spaces). Can you fix that?

**Comment by marijngiesen** [comment]
Oh, haha yeah I see. My IDE found it was necessary to do that. I'll look into it.

**Comment by marijngiesen** [comment]
Still not great, but better readable.

**Comment by marijngiesen** [comment]
Any thoughts?

**Comment by rviscomi** [comment]
Sorry, it's still too difficult to read as-is. I'd really only like to see a diff of your changes.

**Comment by marijngiesen** [comment]
Ok, the formatting should be the way it was. You do use some strange indenting rules by the way..

**Comment by nilbus** [comment]
I agree with the goal of this patch, but I think it requires the user to do too much, creating elements with specific CSS properties. It just feels fragile.

**Comment by marijngiesen** [comment]
Ok, no problem. I'm not using the lib anymore, so I'll just close this.

**Pull request closed without merging**
